services:
    casco-dentar:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        restart: always
        ports:
            - "4000:4000"
        networks:
            - web

networks:
    web:
        external: true
