#name: Auto label merge requests
#
#on:
#    push:
#        branches:
#            - main
#    pull_request:
#        types: [ opened, reopened, synchronize ]
#    pull_request_target:
#        types: [ opened, reopened, synchronize ]
#
#jobs:
#    autolabeler:
#        runs-on: ubuntu-latest
#        permissions:
#            # write permission is required to create a github release
#            contents: write
#            # write permission is required for autolabeler
#            # otherwise, read permission is required at least
#            pull-requests: write
#        steps:
#            -   uses: release-drafter/release-drafter@v6
#                #                with:
#                #                    disable-releaser: true
#                env:
#                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
