name: Frontend

on:
    push:
        branches: [ main ]

permissions:
    contents: write

jobs:
    autolabeler:
        runs-on: ubuntu-latest
        permissions:
            # write permission is required to create a github release
            contents: write
            # write permission is required for autolabeler
            # otherwise, read permission is required at least
            pull-requests: write
        steps:
            -   uses: release-drafter/release-drafter@v6
                #                with:
                #                    disable-releaser: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build:
        needs: autolabeler
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to GitHub Packages Docker Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push to GitHub Packages
                uses: docker/build-push-action@v6
                with:
                    context: .
                    file: ./docker/Dockerfile
                    push: true
                    build-args: VERSION=${{ needs.autolabeler.outputs.tag_name }}
                    tags: ghcr.io/medtourmd/casco-dentar:latest

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Pull & run image on server
                uses: appleboy/ssh-action@master
                with:
                    host: 65.21.186.190
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: /home/docker/deploy/deploy.sh /home/docker/MedTourMd/casco-dentar
