name: Frontend

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to GitHub Packages Docker Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.CR_PAT }}

            -   name: Build and push to GitHub Packages
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ghcr.io/MedTourMd/casco-dentar:latest

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Pull & run image on server
                uses: appleboy/ssh-action@master
                with:
                    host: 65.21.186.190
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.SSH_KEY }}
                    script: /home/docker/deploy/deploy.sh /home/docker/MedTourMd/casco-dentar:latest
